#!/bin/sh

case "$1" in
  start)
        pid=`/bin/pidof planets-qml`
        if [ "$pid" != "" ] ; then
          echo "already running"
          exit 1
        fi

        echo "starting application"
        export XDG_RUNTIME_DIR=/run/user/0/
        /usr/share/examples/qt3d/planets-qml/planets-qml -platform wayland &
  ;;

  stop)
        pid=`/bin/pidof planets-qml`
        if [ "$pid" = "" ] ; then
          echo "not running"
          exit 1
        fi

        echo "stopping application"
        killall planets-qml
  ;;

  *)
        echo "usage: $0 { start | stop }"
  ;;
esac

exit 0
