#!/bin/sh

echo "brcm_patchram_plus utility startup"

brcm_patchram_plus --patchram /lib/firmware/brcm/BCM4343A1_001.002.009.0038.0000_Generic_UART_37_4MHz_wlbga_ref_OTP.hcd --enable_hci --no2bytes --tosleep 50000 --baudrate 2000000 --use_baudrate_for_download /dev/ttyUSB0 &
